#
# Stolen from AbnormalPoof's fork, didnt knew workflows existed lmao
#

# This is a basic workflow to help you get started with Actions

name: Mobile + Release

# Controls when the workflow will run
on:
  push:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Android:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r21e
      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Install Libraries
        run: |
          haxelib install hxcpp > nul
          haxelib install lime 8.0.0
          haxelib install openfl
          haxelib install flixel 4.11.0
          haxelib run lime setup flixel
          haxelib run lime setup         
          haxelib remove flixel-addons
          haxelib remove flixel-tools
          haxelib remove flixel-ui
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons 2.9.0
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install hxCodec 2.5.1          
          haxelib install linc_luajit
          haxelib install hscript|
          haxelib install hxcpp > nul
          haxelib install lime 8.0.0
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install spinehaxe
          haxelib git discord_rpc_yce https://github.com/LEON-BROTHER/discord_rpc_yce
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit.git
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
          haxelib git flixel-textureatlas-yoshiengine https://github.com/ThatOneIdiotXav/flixel-textureatlas-yoshiengine.git
          haxelib git hscript-yoshiengine https://github.com/FNF-CNE-Devs/hscript-improved.git
          haxelib git flixel-yc29 https://github.com/Yoshman29-FunkinArchive/flixel.git
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec.git
          haxelib git spinehaxe https://github.com/bendmorris/spinehaxe.git
          haxelib install hxp
          haxelib install hxcpp-debug-server
      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Compile
        run: haxelib run lime build android -final
        env:
          cert_pass: nullfunni
          cert_alias_pass: nullfunni

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          if-no-files-found: error
  iOS:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Restart Simulator
        run: xcrun simctl shutdown booted
      - name: Select Xcode
        run:
         cd GlassesUSA
         sudo xcode-select -switch /Applications/Xcode_15.2.app && /usr/bin/xcodebuild -version
      - name: Install Dependencies
        run:
         cd GlassesUSA
         pod install --repo-update
        shell: bash
      - name: Run tests
        run:
         cd GlassesUSA
         xcodebuild test -scheme GlassesUSA -workspace GlassesUSA.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' | xcpretty && exit ${PIPESTATUS[0]}
      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > nul
          haxelib install lime 8.0.0
          haxelib install openfl
          haxelib install flixel 4.11.0
          haxelib run lime setup flixel
          haxelib run lime setup         
          haxelib remove flixel-addons
          haxelib remove flixel-tools
          haxelib remove flixel-ui
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons 2.9.0
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install hxCodec 2.5.1          
          haxelib install linc_luajit
          haxelib install hscript|
          haxelib install hxcpp > nul
          haxelib install lime 8.0.0
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install spinehaxe
          haxelib git discord_rpc_yce https://github.com/LEON-BROTHER/discord_rpc_yce
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit.git
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
          haxelib git flixel-textureatlas-yoshiengine https://github.com/ThatOneIdiotXav/flixel-textureatlas-yoshiengine.git
          haxelib git hscript-yoshiengine https://github.com/FNF-CNE-Devs/hscript-improved.git
          haxelib git flixel-yc29 https://github.com/Yoshman29-FunkinArchive/flixel.git
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec.git
          haxelib git spinehaxe https://github.com/bendmorris/spinehaxe.git
          haxelib install hxp
          haxelib install hxcpp-debug-server
      - name: Compile
        run: haxelib run lime build ios -final
      - name: Make Ipa
        run: |
          cd export/release/ios/build/Release-iphoneos
          mkdir Payload
          mv *.app Payload
          zip -r YoshiCrafterEngine_Ios.ipa Payload
      - name: Make Zip For Release
        run: |
           cd export/release/ios/build/Release-iphoneos
           zip YoshiCrafterEngine_Ios.zip YoshiCrafterEngine_Ios.ipa
      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: iOSBuild
          path: export/release/ios/build/Release-iphoneos/*.zip
          if-no-files-found: error
  Releaser:
    needs: [Android, iOS]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download Android Build
        uses: actions/download-artifact@main
        with:
           name: androidBuild
           path: /home/runner
      - name: Move Android File
        run: mv /home/runner/YoshiCrafterEngine_Android-release.apk /home/runner/YoshiCrafterEngine_Android.apk
      - name: Download iOS Build
        uses: actions/download-artifact@main
        with:
           name: iOSBuild
           path: /home/runner
      - name: Publish The Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "dev-8c4d9bf"
          title: "DevBuild 8c4d9bf"
          files: |
            /home/runner/*.apk
            /home/runner/*.zip
