#
# Stolen from AbnormalPoof's fork, didnt knew workflows existed lmao
#

# This is a basic workflow to help you get started with Actions

name: COMPILE ON WINDOWS

# Controls when the workflow will run
on:
  push:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: funny dependencies
        run: |
          mkdir "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          haxelib install lime 7.9.0
          haxelib install openfl 9.1.0 
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install akifox-asynchttp
          haxelib install flixel-addons
          haxelib install newgrounds
          haxelib install linc_luajit
          haxelib install hxp
          haxelib install away3d
          haxelib install hxCodec
          haxelib install markdown
          haxelib install hxcpp-debug-server
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git polymod https://github.com/MasterEric/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git flixel-textureatlas-yoshiengine https://github.com/ThatOneIdiotXav/flixel-textureatlas-yoshiengine
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec
          haxelib git hscript-yoshiengine https://github.com/FNF-CNE-Devs/hscript-improved
          haxelib remove flixel
          haxelib git flixel https://github.com/matthewfro1818/flixel
          haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate
          haxelib git discord_rpc_yce https://github.com/Aidan63/linc_discord-rpc
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib git flixel-textureatlas-yoshiengine https://github.com/YoshiCrafter29/Flixel-TextureAtlas-YoshiCrafterEngine
          haxelib git hscript-yoshiengine https://github.com/YoshiCrafter29/hscript-improved
          haxelib git flixel-yc29 https://github.com/YoshiCrafter29/flixel
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec
          haxelib git spinehaxe https://github.com/bendmorris/spinehaxe
      - name: compilation
        run: |
          haxelib run lime build windows -dce no
          
      - uses: actions/upload-artifact@v2
        with:
          name: YoshiCrafterEngine
          path: export/release/windows/bin
